import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author Sylvain EMONET & Baptiste TRULLA
 *
 */

public class NaiveAlgorithm {

	public NaiveAlgorithm() {
	}

	static final String text = "GAATTCGAGATGCGAATGAGCAGCAGCCATTTTGATGTTGTGAGCATCGGAACGTTTCTGCG\n"
			+ "TCCGTACACTGTCCTTTTGTTACTTAGATAATGGCTAAGGCAAGCAGTCCGGGCCACAGGAGTCAAAG"
			+ "GCTTTTCGCCAGCTCCTAAACGCTGGAAGTGTAATTTTTTTTCTTCTTATAAAATTAAACAAACCCTT\n"
			+ "TTAGAAAGGAACACTCGCTTTATCTCTTCGACCGAATTTACTATACATGGATATATATATATTATCTTC"
			+ "TGTTCACAGTTAAAACTAGGAATAGCATAGTCATAAGTTAACACCATCATGTTGAGAACGTCAACATTG\n"
			+ "TTCACCAAGCGTGTCCAACCAAGCCTATTTTCTAGAAACATTCTTAGATTGCAATCCACAGCTGCAATC"
			+ "CCTAAGACTCAAAAAGGTGTCATCTTTTATGAGAATAAGGGGAACCTGCATTACAAAGATATCCCTGTC\n"
			+ "CCCGAGCCTAAGCCAAATGAAATTTTAATCAACGTTAAATATTCTGGTGTATGTCACACCGATTTACAT"
			+ "GCTTGGCACGGCGATTGGCCATTACCTGTTAAACTACCATTAGTAGGTGGTCATGAAGGTGCTGGTGTA\n"
			+ "GTTGTCAAACTAGGTTCCAATGTCAAGGGCTGGAAAGTCGGTGATTTAGCAGGTATCAAATGGCTGAAC"
			+ "GGTTCTTGTATGACATGCGAATTCTGTGAATCAGGTCATGAATCAAATTGTCCAGATGCTGATTTATCT\n"
			+ "GGTTACACTCATGATGGTTCTTTCCAACAATTTGCGACCGCTGATGCTATTCAAGCCGCCAAAATTCAA"
			+ "CAGGGTACCGACTTGGCCGAAGTAGCCCCAATATTATGTGCTGGTGTTACTGTATATAAAGCACTAAAA\n"
			+ "GAGGCAGACTTGAAAGCTGGTGACTGGGTTGCCATCTCTGGTGCTGCAGGTGGCTTGGGTTCCTTGGCC"
			+ "GTTCAATATGCAACTGCGATGGGTTACAGAGTTCTAGGTATTGATGCAGGTGAGGAAAAGGAAAAACTTT\n"
			+ "TCAAGAAATTGGGGGGTGAAGTATTCATCGACTTTACTAAAACAAAGAATATGGTTTCTGACATTCAAGA"
			+ "AGCTACCAAAGGTGGCCCTCATGGTGTCATTAACGTTTCCGTTTCTGAAGCCGCTATTTCTCTATCTACG\n"
			+ "GAATATGTTAGACCATGTGGTACCGTCGTTTTGGTTGGTTTGCCCGCTAACGCCTACGTTAAATCAGAGG"
			+ "TATTCTCTCATGTGGTGAAGTCCATCAATATCAAGGGTTCTTATGTTGGTAACAGAGCTGATACGAGAGA\n"
			+ "AGCCTTAGACTTCTTTAGCAGAGGTTTGATCAAATCACCAATCAAAATTGTTGGATTATCTGAATTACCA"
			+ "AAGGTTTATGACTTGATGGAAAAGGGCAAGATTTTGGGTAGATACGTCGTCGATACTAGTAAATAATAGC\n"
			+ "GTGTTACGCACCCAAACTTTTATGAAAGTCTTTGTTTATAATGATGAGGTTTATAAATATATAGTGGAGC"
			+ "AAAGATTAATCACTAAATCAAGAAGCAGTACCAGTATTTTTTCTATATCAAGTAGTGATAATGGAAATAG\n" + "CCCAAATTTGGCTTCCGTCGAC";

	static String pattern1 = "TGATGG";
	static String pattern2 = "TTTT";

	public static void main(String[] args) {

		int n = text.length();
		int m1 = pattern1.length();
		int m2 = pattern2.length();
		
		Date tempsAvantNaive = new Date();
		SimpleDateFormat formater = null;
		formater = new SimpleDateFormat("'le' dd/MM/yyyy 'à' hh:mm:ss:SS");
		System.out.println("Début de l'algorithme Naif "+formater.format(tempsAvantNaive));
		
		for (int i = 0; i < n - m1; i++) {
			
			if (pattern1.equals(text.subSequence(i, i + m1)))
				System.out.println("Le pattern TGATGG trouvé à la position : " + (i + 1)+".");
			
			if (pattern2.equals(text.subSequence(i, i + m2)))
				System.out.println("Le pattern TTTT trouvé à la position : " + (i + 1)+".");

		}
		
		Date tempsApresNaive = new Date();
		System.out.println("\nFin de l'algorithme Naif "+formater.format(tempsApresNaive));

		long chrono = tempsApresNaive.getTime() - tempsAvantNaive.getTime();
		System.out.println("Temps total de l'éxécution de l'algorithme naif : " + chrono + " ms.");
	}
}
